name: blog_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  graphql_flutter: ^5.0.0
  mockito: ^5.4.4

  provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  graphql_flutter: ^5.0.0

flutter:
  uses-material-design: true
